"""add rels

Revision ID: 126b8122ad77
Revises: bd715ad646a2
Create Date: 2025-06-05 12:40:36.737781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '126b8122ad77'
down_revision: Union[str, None] = 'bd715ad646a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('wallet_id', sa.UUID(), nullable=False))
    op.add_column('transaction', sa.Column('credit_amount', sa.DECIMAL(precision=15, scale=2), nullable=False))
    op.add_column('transaction', sa.Column('price_per_credit', sa.DECIMAL(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_transaction_wallet_id'), 'transaction', ['wallet_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'wallet', ['wallet_id'], ['id'], ondelete='CASCADE')
    op.drop_column('transaction', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('amount', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_wallet_id'), table_name='transaction')
    op.drop_column('transaction', 'price_per_credit')
    op.drop_column('transaction', 'credit_amount')
    op.drop_column('transaction', 'wallet_id')
    # ### end Alembic commands ###
