"""add columns to transaction

Revision ID: 9957ae62cd8d
Revises: 126b8122ad77
Create Date: 2025-06-05 17:08:16.568262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9957ae62cd8d'
down_revision: Union[str, None] = '126b8122ad77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('TOPUP', 'PURCHASE', 'REFUND', name='transaction_type_enum'), nullable=False),
    sa.Column('purchase_type_enum', sa.Enum('BY_CREDIT', 'BY_BUGDET',name='purchase_type_enum'), nullable=True),
    sa.Column('credit_amount', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('requested_credits', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('requested_budget', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('price_paid', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('price_per_credit', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transaction_status_enum'), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transaction_project', 'transaction', ['project_id'], unique=False)
    op.create_index('idx_transaction_status_created', 'transaction', ['status', 'created_at'], unique=False)
    op.create_index('idx_transaction_user_type', 'transaction', ['user_id', 'transaction_type'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_is_active'), 'transaction', ['is_active'], unique=False)
    op.create_index(op.f('ix_transaction_project_id'), 'transaction', ['project_id'], unique=False)
    op.create_index(op.f('ix_transaction_status'), 'transaction', ['status'], unique=False)
    op.create_index(op.f('ix_transaction_transaction_type'), 'transaction', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transaction_user_id'), 'transaction', ['user_id'], unique=False)
    op.create_index(op.f('ix_transaction_wallet_id'), 'transaction', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_wallet_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_user_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_transaction_type'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_status'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_project_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_is_active'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index('idx_transaction_user_type', table_name='transaction')
    op.drop_index('idx_transaction_status_created', table_name='transaction')
    op.drop_index('idx_transaction_project', table_name='transaction')
    op.drop_table('transaction')
    # ### end Alembic commands ###
